In [1]:
## run-1
## download data sku dari tatanama
## common problems: slow server pyany & make sure path to file

import time
import pandas as pd
import numpy as np
import math

import smtplib
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from smtplib import SMTP
import smtplib
import sys
import requests
import os


print('Reading Data SKU')
data_SKU = pd.read_excel('SKU_File\data_SKU.xlsx')
print('Scrapping Tatanama')
s = requests.Session()
s.get("https://tatanama.pythonanywhere.com")
s.post("https://tatanama.pythonanywhere.com", data = {'username' : 'ecommerce', 'password' : 'ecommerce'})
r = s.get("https://tatanama.pythonanywhere.com/download")

with open('SKU_File\Master tatanama.xlsx', 'wb') as output:
    output.write(r.content)
    
print('ok')

if os.path.isfile('SKU_File\Master tatanama.xlsx') :    
    SKU_append = pd.read_excel('SKU_File\Master tatanama.xlsx')
    SKU_append.columns = [x.replace('_', ' ') for x in SKU_append.columns]
    data_SKU = data_SKU[~data_SKU['SKU'].astype(str).isin(SKU_append['SKU'].astype(str))]
    data_SKU = data_SKU.append(SKU_append, ignore_index = True, sort = False)

data_SKU.loc[data_SKU['Price List NFI'].isin(['-']), 'Price List NFI'] = 0
to_excel = data_SKU.to_excel('SKU_File\data_SKU.xlsx', index = False)
print('data SKU done')

data_SKU['Price List NFI'] = data_SKU['Price List NFI'].astype(float).astype('int64')

download = True

Reading Data SKU
Scrapping Tatanama
ok

C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3600715785.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data_SKU = data_SKU.append(SKU_append, ignore_index = True, sort = False)

data SKU done

In [4]:
###Optional
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import time
import pandas as pd
import numpy as np
import math

import smtplib
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from smtplib import SMTP
import smtplib
import sys
import requests
import os

data_all =pd.read_csv(r"D:\Masterdata\Clean Data\data_all_30 March With Order Online.csv", sep = ';',converters = {'Phone' : str, 'Order #' : str, 'AWB' : str})

data_all['True datetime']=pd.to_datetime(data_all['True datetime'])
data_all['Real SKU']=data_all['Real SKU'].astype(str)
data_all['Phone']=data_all['Phone'].str.extract('(\d+)')

data_now = '30 March With Order Online'

C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\916554145.py:20: DtypeWarning: Columns (3,15,23,24,25,27,29,30,31,32,33,34,35,36,37,39,53,54,57,59,60,66,67,73,74,80,81,87,88,94,95,101,102,110,122,123,134,135,136,153,159,161,167,168,169,172,173,174,175,176,181,196,197,198,199) have mixed types. Specify dtype option on import or set low_memory=False.
  data_all =pd.read_csv(r"D:\Masterdata\Clean Data\data_all_30 March With Order Online.csv", sep = ';',converters = {'Phone' : str, 'Order #' : str, 'AWB' : str})

In [24]:
orami = pd.read_csv(r"C:\Users\steven.nathanael\Downloads\OramiSeller_27022023-29032023.csv", sep = ',',converters = {'Phone' : str, 'AWB' : str})
orami.drop(columns = 'Total', inplace = True)
orami.rename(columns = {'Tanggal pesanan' : 'Order Date',
                        'Nomor pesanan' : 'Order #',
                        'Provinsi' : 'City',
                        'Nama produk' : 'Product Name',
                        'No. Resi' : 'AWB',
                        'Nama customer' : 'Customer Name',
                        'Alamat customer' : 'Address',
                        'Kodepos' : 'Zip Code',
                        'Metode pengiriman' : 'Shipping Courier',
                        'Kuantitas' : 'Qty. Invoiced',
                        'Voucher' : 'Coupon Code',
                        'Total harga produk' : 'Total',
                        'Status pesanan' : 'Order Status'}, inplace = True)

In [33]:
orami['Product Name'].unique()

array(['L-Men Hi Protein 2 Go Chocolate (24 pcs) | 2307061250P24',
       'NutriSari Jeruk Peras Refill 500gr - Minuman Buah Vitamin C | 1101569360',
       'Free Spider Bottle - L-Men Platinum Vanilla Caramel 800g',
       'Twin Pack - L-Men Protein Bar Chocolate 12 sch | 2306551173P2',
       'HiLo RTD Kacang Hijau 200 ml - 24 pcs | 2101907250P24',
       'Tropicana Slim RTD Almond Drink Chocolicious 190 ml x 24 pack| 2T01402249P24',
       'Twin Pack: Tropicana Slim DIABTX (50 sch) | 2102900125P2',
       'HiLo School RTD Vanila Vegiberi 200ml - 24 pcs | 21014281P24',
       'HiLo School Honey 500 gr x 2 Pcs - Twinpack | 2101401180P2',
       'HiLo School Honey 500gr | 2101401180',
       'L-Men Hi Protein 2 Go Chocolate',
       'L-Men Protein Bar Chocolate 12 sch',
       'HiLo RTD Kacang Hijau 200 ml',
       'Tropicana Slim RTD Almond Drink Chocolicious 190 ml',
       'Tropicana Slim DIABTX (50 sch)',
       'HiLo School RTD Vanila Vegiberi 200ml', 'HiLo School Honey 500gr'],
      dtype=object)

In [34]:
import time
import pandas as pd
import numpy as np
import math

import smtplib
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from smtplib import SMTP
import smtplib
import sys
import requests
import os

orami = pd.read_csv(r"C:\Users\steven.nathanael\Downloads\OramiSeller_01042023-24042023.csv", sep = ',',converters = {'Phone' : str, 'AWB' : str})
orami.drop(columns = 'Total', inplace = True)
orami.rename(columns = {'Tanggal pesanan' : 'Order Date',
                        'Nomor pesanan' : 'Order #',
                        'Provinsi' : 'City',
                        'Nama produk' : 'Product Name',
                        'No. Resi' : 'AWB',
                        'Nama customer' : 'Customer Name',
                        'Alamat customer' : 'Address',
                        'Kodepos' : 'Zip Code',
                        'Metode pengiriman' : 'Shipping Courier',
                        'Kuantitas' : 'Qty. Invoiced',
                        'Voucher' : 'Coupon Code',
                        'Total harga produk' : 'Total',
                        'Status pesanan' : 'Order Status'}, inplace = True)
orami['Total'] = orami['Total'].astype(int)
orami['Day'] = orami['Order Date'].str.slice(0, 3).astype(int)
orami['Month'] = orami['Order Date'].str.slice(3, 6)
orami['Month'] = orami['Month'].apply(lambda x : 'September' if x == 'Sep' else
                                                 ('October' if x == 'Okt' else
                                                 ('November' if x == 'Nov' else 
                                                 ('December' if x == 'Des' else
                                                 ('January' if x == 'Jan' else
                                                 ('February' if x == 'Feb' else
                                                 ('March' if x == 'Mar' else
                                                 ('April' if x == 'Apr' else
                                                 ('May' if x == 'Mei' else
                                                 ('June' if x == 'Jun' else
                                                 ('July' if x == 'Jul' else 'August')))))))))))
orami['Year'] = orami['Order Date'].str.slice(6, 11).astype(int)
orami['month'] = orami['Month'].apply(lambda x : 9 if x == 'September' else
                                                 (10 if x == 'October' else
                                                 (11 if x == 'Novemer' else 
                                                 (12 if x == 'December' else
                                                 (1 if x == 'January' else
                                                 (2 if x == 'February' else
                                                 (3 if x == 'March' else
                                                 (4 if x == 'April' else
                                                 (5 if x == 'May' else
                                                 (6 if x == 'June' else
                                                 (7 if x == 'July' else 8)))))))))))
orami['Hour'] = orami['Order Date'].str.slice(12, 15).astype(int)
orami['Minute'] = orami['Order Date'].str.slice(16, 19).astype(int)
orami['True datetime'] = pd.to_datetime(orami[['Year','month','Day','Hour','Minute']])
orami.rename(columns = {'Day' : 'Date'}, inplace = True)
orami['Real SKU'] = orami['Product Name'].str.split('|').str[1].str.strip().astype(str)
orami['SKU'] = orami['Real SKU']
orami['Selling Price'] = orami['Total'] / orami['Qty. Invoiced']
orami[['Store','Channel']] = 'Orami Shopping'

orami.loc[orami['Product Name'].isin(['Free Spider Bottle - L-Men PlantProtein Ogura 2pcs']), 'Real SKU'] = 'PL24(2)G26'
orami.loc[orami['Product Name'].isin(['Parsel Wonderful Sweetness']), 'Real SKU'] = '(J)71110127'
orami.loc[orami['Product Name'].isin(['BUY 1 GET 1 - Tropicana Slim Mint Cocoa']), 'Real SKU'] = '2104148164P2'
orami.loc[orami['Product Name'].isin(['Free Tupperware - HiLo Platinum Swiss Chocolate 420g']), 'Real SKU'] = 'PH22G184'
orami.loc[orami['Product Name'].isin(['Buy 1 Get 1 Free - HiLo School Bubble Gum 500g']), 'Real SKU'] = '2101459180P2'
orami.loc[orami['Product Name'].isin(['Free HiLo School RTD - HiLo Teen Strawberry Milkshake 500g']), 'Real SKU'] = 'PH78B104'
orami.loc[orami['Product Name'].isin(['Free L-Men 2 GO - L-Men Lose Weight Chocolate Cereal 300g']), 'Real SKU'] = 'PL7B103'
orami.loc[orami['Product Name'].isin(['HiLo Active Es Teler 175gr']), 'Real SKU'] = '2101413144'
orami.loc[orami['Product Name'].isin(['Hampers Idul Fitri Lebaran NutriSari 25 Rasa (75s)']), 'Real SKU'] = '(J)71110126'
orami.loc[orami['Product Name'].isin(['BUY 1 GET 1 - HiLo Multigrain Original 500 gram']), 'Real SKU'] = '2101469180P2'
orami.loc[orami['Product Name'].isin(['Free Spider Bottle - L-Men Platinum Vanilla Caramel 800g']), 'Real SKU'] = 'PL30G26'

data_SKU['Real Nama Produk'] = data_SKU['Nama Produk'].astype(str)
data_SKU['Real SKU'] = data_SKU['SKU'].astype(str)
orami['Real SKU'] = orami['Real SKU'].astype(str)
data_SKU['Price List NFI'] = data_SKU['Price List NFI'].astype(float).astype('int64')
orami = orami.merge(data_SKU[['Real SKU', 'Real Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU', 'Price List NFI']].drop_duplicates(['Real SKU']), how = 'left', on = 'Real SKU')
orami['Total Net'] = orami['Price List NFI'] * orami['Qty. Invoiced']

indeks = orami[orami['Brand'] == 'Bundle'].index.to_list()
orami['Bundle Flag'] = np.nan
orami['Bundle Flag'][indeks] = 'Bundle'

orami['SKU'] = orami['SKU'].astype(str)
list_col = ['SKU'] + data_SKU.columns[data_SKU.columns.get_loc('Produk 1'):data_SKU.columns.get_loc('Harga Cost 7')+1].to_list()
orami = orami.merge(data_SKU[list_col].drop_duplicates(['SKU']), how = 'left', left_on = 'Real SKU', right_on = 'SKU')
orami = orami.drop(['SKU_y'], axis = 1)
orami  = orami.rename(columns = {'SKU_x':'SKU'})

data_orami = orami.copy()

print("Unbundling")
data_bundle1 = data_orami[~data_orami['Produk 1'].isnull()]
data_bundle1['Bundle Name'] = data_bundle1['Product Name']
data_bundle1['Product Name'] = data_bundle1['Produk 1']
data_bundle1['SKU'] = data_bundle1['SKU Produk 1']
data_bundle1['Qty. Invoiced'] = data_bundle1['PCS Produk 1']
data_bundle1['Price List NFI'] = data_bundle1['Price List NFI 1']
data_bundle1['Total Net'] = data_bundle1['Price List NFI 1']
data_bundle1['Bundle Flag'] = np.nan

data_bundle2 = data_orami[~data_orami['Produk 2'].isnull()]
data_bundle2['Bundle Name'] = data_bundle2['Product Name']
data_bundle2['Product Name'] = data_bundle2['Produk 2']
data_bundle2['SKU'] = data_bundle2['SKU Produk 2']
data_bundle2['Qty. Invoiced'] = data_bundle2['PCS Produk 2']
data_bundle2['Price List NFI'] = data_bundle2['Price List NFI 2']
data_bundle2['Total Net'] = data_bundle2['Price List NFI 2']
data_bundle2['Bundle Flag'] = np.nan

data_bundle3 = data_orami[~data_orami['Produk 3'].isnull()]
data_bundle3['Bundle Name'] = data_bundle3['Product Name']
data_bundle3['Product Name'] = data_bundle3['Produk 3']
data_bundle3['SKU'] = data_bundle3['SKU Produk 3']
data_bundle3['Qty. Invoiced'] = data_bundle3['PCS Produk 3']
data_bundle3['Price List NFI'] = data_bundle3['Price List NFI 3']
data_bundle3['Total Net'] = data_bundle3['Price List NFI 3']
data_bundle3['Bundle Flag'] = np.nan

data_bundle4 = data_orami[~data_orami['Produk 4'].isnull()]
data_bundle4['Bundle Name'] = data_bundle4['Product Name']
data_bundle4['Product Name'] = data_bundle4['Produk 4']
data_bundle4['SKU'] = data_bundle4['SKU Produk 4']
data_bundle4['Qty. Invoiced'] = data_bundle4['PCS Produk 4']
data_bundle4['Price List NFI'] = data_bundle4['Price List NFI 4']
data_bundle4['Total Net'] = data_bundle4['Price List NFI 4']
data_bundle4['Bundle Flag'] = np.nan

data_bundle5 = data_orami[~data_orami['Produk 5'].isnull()]
data_bundle5['Bundle Name'] = data_bundle5['Product Name']
data_bundle5['Product Name'] = data_bundle5['Produk 5']
data_bundle5['SKU'] = data_bundle5['SKU Produk 5']
data_bundle5['Qty. Invoiced'] = data_bundle5['PCS Produk 5']
data_bundle5['Price List NFI'] = data_bundle5['Price List NFI 5']
data_bundle5['Total Net'] = data_bundle5['Price List NFI 5']
data_bundle5['Bundle Flag'] = np.nan

data_bundle6 = data_orami[~data_orami['Produk 6'].isnull()]
data_bundle6['Bundle Name'] = data_bundle6['Product Name']
data_bundle6['Product Name'] = data_bundle6['Produk 6']
data_bundle6['SKU'] = data_bundle6['SKU Produk 6']
data_bundle6['Qty. Invoiced'] = data_bundle6['PCS Produk 6']
data_bundle6['Price List NFI'] = data_bundle6['Price List NFI 6']
data_bundle6['Total Net'] = data_bundle6['Price List NFI 6']
data_bundle6['Bundle Flag'] = np.nan

data_bundle7 = data_orami[~data_orami['Produk 7'].isnull()]
data_bundle7['Bundle Name'] = data_bundle7['Product Name']
data_bundle7['Product Name'] = data_bundle7['Produk 7']
data_bundle7['SKU'] = data_bundle7['SKU Produk 7']
data_bundle7['Qty. Invoiced'] = data_bundle7['PCS Produk 7']
data_bundle7['Price List NFI'] = data_bundle7['Price List NFI 7']
data_bundle7['Total Net'] = data_bundle7['Price List NFI 7']
data_bundle7['Bundle Flag'] = np.nan


data_bundle = data_bundle1.append([data_bundle2, data_bundle3, data_bundle4, data_bundle5, data_bundle6, data_bundle7], ignore_index = True, sort = False)
data_bundle['SKU'] = data_bundle['SKU'].astype(str)
data_bundle['SKU'] = data_bundle['SKU'].str.replace('\.0$', '', regex = True)
data_bundle[['Real SKU', 'Real Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU']] = data_bundle.merge(data_SKU[['Real SKU', 'Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU']].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU')[['Real SKU_y', 'Nama Produk', 'Brand_y', 'Sub Brand_y', 'Parent Item_y', 'Parent SKU_y']]


orami = orami.append(data_bundle, ignore_index = True, sort = False)
orami = orami.merge(data_SKU[['Real SKU', 'Harga Cost']].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU')
orami['Total Harga Cost'] = pd.to_numeric(orami['Harga Cost'], errors = 'coerce') * orami['Qty. Invoiced']
print(orami[orami['Harga Cost'] == 0][['SKU','Product Name']].drop_duplicates())
orami['Total'] = orami['Selling Price'] * orami['Qty. Invoiced']
orami['Subtotal'] = orami['Selling Price'] * orami['Qty. Invoiced']
orami = orami.rename(columns = {'Real SKU_x' : 'Real SKU'})

C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orami['Bundle Flag'][indeks] = 'Bundle'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle1['Bundle Name'] = data_bundle1['Product Name']
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:100: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle1['Product Name'] = data_bundle1['Produk 1']
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:101: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle1['SKU'] = data_bundle1['SKU Produk 1']
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle1['Qty. Invoiced'] = data_bundle1['PCS Produk 1']
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle1['Price List NFI'] = data_bundle1['Price List NFI 1']
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle1['Total Net'] = data_bundle1['Price List NFI 1']
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle1['Bundle Flag'] = np.nan
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle2['Bundle Name'] = data_bundle2['Product Name']
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle2['Product Name'] = data_bundle2['Produk 2']
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle2['SKU'] = data_bundle2['SKU Produk 2']
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle2['Qty. Invoiced'] = data_bundle2['PCS Produk 2']
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle2['Price List NFI'] = data_bundle2['Price List NFI 2']
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:113: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle2['Total Net'] = data_bundle2['Price List NFI 2']
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\130822625.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bundle2['Bundle Flag'] = np.nan

Unbundling
Empty DataFrame
Columns: [SKU, Product Name]
Index: []

In [36]:
columns_da = data_all.columns
columns_o = orami.columns
orami1 = orami[[x for x in columns_o if x in columns_da]]
data_all1 = data_all.append(orami1, ignore_index = True)

,Order #,Sales Order ID,AWB,Paid Date,Order Status,Order date,Week,Date,Month,Quarter,...,Payment Received Ref. number,Category Baru,Exported Parent Item,Unnamed: 0,Price List NFI_x,Customer Type,Real Region,True datetime1,Payment Date,Shipping Customer Name
0,220101KF9CRRPJ,#SO-115792812,JP9221384040,2022-01-01 00:01:00,Cancelled,2022-01-01 00:00:00,52.0,1.0,January,1.0,...,NaN,HILO TRADITIONAL,HILO CHOCOLATE TARO PLS 15RX10SX14G,NaN,NaN,NaN,Jabodetabek,2022-01-01 00:00:00,NaN,NaN
1,220101KF8V3UF6,#SO-115792804,JP2821530627,2022-01-01 00:01:00,Cancelled,2022-01-01 00:00:00,52.0,1.0,January,1.0,...,NaN,HILO TEEN,HILO TEEN COKLAT 500G (12D),NaN,NaN,NaN,Jawa Barat,2022-01-01 00:00:00,NaN,NaN
2,220101KF86KYT6,#SO-115792769,JP0117026545,NaN,Cancelled,2022-01-01 00:00:00,52.0,1.0,January,1.0,...,NaN,HILO TEEN,HILO TEEN POPCORN CARAMEL 12DX500G,NaN,NaN,NaN,Jabodetabek,2022-01-01 00:00:00,NaN,NaN
3,220101KF99MQ6H,#SO-115792810,JP6646092620,2022-01-01 00:01:00,Cancelled,2022-01-01 00:00:00,52.0,1.0,January,1.0,...,NaN,L-MEN POWDER,L-MEN GM CHOCOLATE 6DX500G,NaN,NaN,NaN,Jawa Tengah,2022-01-01 00:00:00,NaN,NaN
4,220101KF7SYVTJ,#SO-115792738,JP5713456513,2022-01-01 00:05:00,Delivered,2022-01-01 00:00:00,52.0,1.0,January,1.0,...,NaN,L-MEN POWDER,L-MEN GM TARO 12DX225G,NaN,NaN,NaN,Jabodetabek,2022-01-01 00:00:00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2360499,20419898,NaN,1567505350.0,NaN,Selesai,NaN,NaN,23.0,March,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2360500,20401331,NaN,NaN,NaN,Dibatalkan,NaN,NaN,21.0,March,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2360501,20258608,NaN,NaN,NaN,Dibatalkan,NaN,NaN,11.0,March,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2360502,20140403,NaN,1567505317.0,NaN,Selesai,NaN,NaN,4.0,March,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2360503,20497942,NaN,1567505361.0,NaN,Pesanan Tiba,NaN,NaN,27.0,March,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
indeks = data_all[data_all['Qty. Invoiced'].isnull()].index.to_list()
data_all['Qty. Invoiced'][indeks] = 0
data_all['Total Net'][indeks] = data_all['Price List NFI'][indeks] * data_all['Qty. Invoiced'][indeks]

import pandas as pd
import numpy as np
import os
import glob

data_all = data_all[data_all['Store Type'] != 'Retail Online']
data_nubi = pd.read_csv(r"C:\Users\steven.nathanael\Downloads\Main_Sheet_(timo)_(2)_Full_Data_data (3).csv")

data_nubi.loc[data_nubi['Customer SO Desc']=='INDOPASIFIK FARMA MEDIKA INDONESIA, PT',['Customer SO Group Area','Customer SO Parent Desc']]='ECOM RETAIL - INDOPASIFIK FARMA MEDIKA INDONESIA'
data_nubi.loc[data_nubi['Customer SO Desc'].isin(['SUKACITA TEKNOLOGI INDONESIA, PT','COSMART']),['Customer SO Group Area','Customer SO Parent Desc']]='ECOM RETAIL - JOYBOX(COSMART)'
data_nubi.loc[data_nubi['Customer SO Desc'].isin(['FRESHBOX DEPO JKT']),['Customer SO Group Area','Customer SO Parent Desc']]='ECOM RETAIL - FRESHBOX'

data_nubi = data_nubi[data_nubi['Customer SO Group Area'].astype(str).str.contains('ECOM RETAIL')]

data_SKU = pd.read_excel(r'SKU_File\data_SKU.xlsx')

data_nubi['Sales Order ID'] = 'Nubi -' + data_nubi['Customer SO Parent Desc'].astype(str)
data_nubi['Channel Order ID'] = 'Nubi -' + data_nubi['Customer SO Parent Desc'].astype(str)
data_nubi['Customer Name'] = 'Nubi Retail Online'

print("Filling Date ====== 7/10")

data_nubi['Date'] = data_nubi['Day of Invoice Date SO']
data_nubi['Month'] = data_nubi['Month of Invoice Date SO']
data_nubi['Year'] = data_nubi['Year of Invoice Date SO']

quarter = pd.DataFrame([['January', 1], ['February', 1], ['March', 1], ['April', 2], ['May', 2], ['June', 2], 
        ['July', 3], ['August', 3], ['September', 3],['October', 4], ['November', 4], ['December', 4]], columns = ['Bulan', 'Quarter'])
data_nubi = data_nubi.merge(quarter, how = 'left', left_on = 'Month', right_on = 'Bulan')
data_nubi = data_nubi.drop(['Bulan'], axis = 1)
data_bulan = pd.DataFrame([{'Bulan' : 'December', 'Number' : 12} ,
        {'Bulan' : 'January' , 'Number': 1},
        {'Bulan' : 'February' , 'Number': 2},
        {'Bulan' : 'March' , 'Number': 3},
        {'Bulan' : 'April' , 'Number': 4},
        {'Bulan' : 'May' , 'Number': 5},
        {'Bulan' : 'June', 'Number': 6},
        {'Bulan' : 'July' , 'Number': 7},
        {'Bulan' : 'August', 'Number' : 8},
        {'Bulan' : 'September', 'Number' : 9},
        {'Bulan' : 'October' , 'Number': 10},
        {'Bulan' : 'November' , 'Number': 11}])
temp = data_nubi.copy()
temp['Day'] = temp['Date']
temp = temp.merge(data_bulan, how = 'left', left_on = 'Month', right_on='Bulan')
temp= temp.rename(columns = {'Month' : 'Bulan', 'Number' : 'Month'})
data_nubi['Week'] = pd.to_datetime(temp[['Year', 'Month', 'Day']]).dt.week
data_nubi['True datetime'] = pd.to_datetime(temp[['Year', 'Month', 'Day']])

data_nubi['Order Date'] = data_nubi['Day of Invoice Date SO']
data_nubi['Paid Date'] = data_nubi['Day of Invoice Date SO']
data_nubi['Status'] = 'Delivered'
data_nubi['Channel'] = data_nubi['Customer SO Parent Desc']
data_nubi['Store'] = data_nubi['Customer SO Group Area']
data_nubi['Currency Code'] = "IDR"
data_nubi['Warehouse Name'] = data_nubi['Customer SO Desc']
data_nubi['Regular Price'] = data_nubi['Sales Value Netto SO'] / data_nubi['Sales Qty SO']
data_nubi['Store Type'] = 'Retail Online'

indeks = data_nubi[data_nubi['Regular Price'].isnull()].index.to_list()
data_nubi['Regular Price'][indeks] = 0

data_nubi['Selling Price'] = data_nubi['Sales Value Netto SO'] / data_nubi['Sales Qty SO']
indeks = data_nubi[data_nubi['Selling Price'].isnull()].index.to_list()
data_nubi['Selling Price'][indeks] = 0

indeks = data_nubi[data_nubi['Sales Qty SO'] == 0].index.to_list()
data_nubi['Selling Price'][indeks] = 0
data_nubi['Regular Price'][indeks] = 0

indeks = data_nubi[data_nubi['Sales Value Netto SO'] == 0].index.to_list()
data_nubi['Selling Price'][indeks] = 0
data_nubi['Regular Price'][indeks] = 0

data_nubi['Sub Total'] = data_nubi['Sales Value Netto SO']
data_nubi['Gross Sales'] = data_nubi['Sales Value Netto SO']

data_nubi = data_nubi.rename(columns = {'Item Group Code' : 'SKU', 'Item Group' : 'Item Name', 'Sales Qty SO' : 'Quantity'})

data_nubi = data_nubi[['Sales Order ID', 'Channel Order ID', 'Customer Name', 'Order Date', 'Paid Date','Status','Channel', 'Store', 'Currency Code', 'Warehouse Name', 'Regular Price', 'Selling Price',
              'Sub Total', 'Gross Sales', 'SKU', 'Item Name', 'Quantity', 'Date', 'Month', 'Year', 'True datetime', "Week", 'Brand', 'Category']]

data_nubi['Order Date'] = data_nubi['True datetime']
data_nubi['Quarter'] = pd.to_datetime(data_nubi['True datetime']).dt.quarter

print("Filling Brand ====== 5/10")
data_nubi['SKU'] = data_nubi['SKU'].astype(str)
data_nubi['Item Name'] = data_nubi['Item Name'].astype(str)
data_SKU['Real SKU'] = data_SKU['SKU']
data_SKU['Real Nama Produk'] = data_SKU['Nama Produk'].astype(str)


data_nubi = data_nubi.merge(data_SKU[['Real SKU', 'Real Nama Produk']].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU')
data_nubi['Real SKU'] = data_nubi['Real SKU'].astype(str)
data_nubi = data_nubi.merge(data_SKU[['SKU', 'Sub Brand', 'Parent Item', 'Parent SKU','Price List NFI']].drop_duplicates(['SKU']), how = 'left', left_on = 'Real SKU', right_on = 'SKU')
data_nubi['Parent Item'] = data_nubi['Parent Item'].fillna(data_nubi['Item Name'])
data_nubi = data_nubi.drop(['SKU_y'], axis = 1)
data_nubi = data_nubi.rename(columns = {'SKU_x':'SKU'})

indeks = data_nubi[data_nubi['Real SKU'].astype(str) == 'nan'].index.to_list()
data_nubi['Real SKU'][indeks] = data_nubi['SKU'][indeks]

indeks = data_nubi[data_nubi['Real Nama Produk'].astype(str) == 'nan'].index.to_list()
data_nubi['Real Nama Produk'][indeks] = data_nubi['Item Name'][indeks]

data_nubi['Sub Brand'] = data_nubi['Category']

data_nubi['Total'] = data_nubi['Sub Total']
data_nubi['Total Net'] = np.nan

data_nubi = data_nubi.rename(columns={'Channel Order ID' : 'Order #',
                                        'Status' : 'Order Status',
                                        'Order Date' : 'Order date',
                                        'Item Name' :'Product Name',
                                        'Bundle Name' : 'Bundle',
                                        'Shipping Country' : 'Country',
                                        'Shipping Province' : 'Region',
                                        'Shipping City' : 'City',
                                        'Shipping Zip' : 'Zip Code',
                                        'Shipping Address1' : 'Address',
                                        'Shipping Phone' : 'Phone',
                                        'Quantity' : 'Qty. Invoiced',
                                        'Item Price' : 'Regular Price',
                                        'Sub Total' : 'Subtotal'})


temp = data_nubi[data_nubi['Price List NFI'].isnull()]
skuoff=pd.read_excel('data_supp\item gk tau harga.xlsx')
skuoff=skuoff[['Real SKU','Price List NFI']]
skuoff['Real SKU']=skuoff['Real SKU'].astype(str)#.info()
display(temp[~temp['Real SKU'].isin(skuoff['Real SKU'].unique())])
temp=temp.merge(skuoff,how='left',on='Real SKU').rename(columns=({'Price List NFI_y':'Price List NFI'}))
data_nubi=data_nubi[data_nubi['Price List NFI'].notnull()].append(temp)


data_nubi['Price List NFI'] = pd.to_numeric(data_nubi['Price List NFI']).astype(int)
data_nubi['Qty. Invoiced'] = pd.to_numeric(data_nubi['Qty. Invoiced']).fillna(0).astype(int)

data_nubi['Total Net'] = data_nubi['Price List NFI'] * data_nubi['Qty. Invoiced']

data_nubi = data_nubi.reset_index(drop = True)

data_nubi['True datetime'] = pd.to_datetime(data_nubi['True datetime'])
data_nubi['Promo'] = np.nan
data_nubi['Discount MC'] = np.nan
data_nubi['Store Type'] = 'Retail Online'

for i in data_nubi['Brand'].unique():
    indeks = data_nubi[data_nubi['Brand'] == i].index.to_list()
    if i == 'NUTRISARI':
        data_nubi['Brand'][indeks] = 'NS'
    elif i == 'HI LO':
        data_nubi['Brand'][indeks] = 'HiLo'
        
temp = data_nubi[data_nubi['Store'] == 'WARUNG PINTAR DISTRIBUSI - BOGOR, PT'].copy()
data_nubi = data_nubi[data_nubi['Store'] != 'WARUNG PINTAR DISTRIBUSI - BOGOR, PT']

temp['Store'] = 'WARUNG PINTAR'
temp['Channel'] = 'WARUNG PINTAR DISTRIBUSI, PT'
temp['Warehouse Name'] = 'WARUNG PINTAR DISTRIBUSI - BOGOR, PT'

data_nubi = data_nubi.append(temp, ignore_index = True, sort = False)

indeks = data_nubi[data_nubi['Store'] == 'SHOPEE'].index.to_list()
data_nubi['Store'][indeks] = 'Shopee Sell-In'

### ini run
from datetime import date
from datetime import datetime, timedelta
import glob
import os
cutoff=str((date.today().replace(day=1)-timedelta(1)).replace(day=1))
data_nubinew=data_nubi[data_nubi['True datetime']>=cutoff]

data_nubi

list_of_files = glob.glob('data_nubi\*.xlsx') # * means all if need specific format then *.csv
latest_file = max(list_of_files, key=os.path.getctime)
print(latest_file)

data_nubi=pd.read_excel(latest_file)
# data_nubi['Total Net Before ]
data_nubi=data_nubi[data_nubi['True datetime']<cutoff]
          
data_nubi=data_nubi.append(data_nubinew)

data_nubi.to_excel(f"data_nubi\data_nubi_{date.today()}.xlsx",index=False)

#run satuin nama retail
data_nubi.loc[data_nubi['Store']=='ASTRO TECHNOLOGIES - TANGERANG, PT',['Store']]='ECOM RETAIL - ASTRO'
data_nubi.loc[data_nubi['Store']=='RITEL BERSAMA NASIONAL; PT',['Store']]='ECOM RETAIL - JD ID'
data_nubi.loc[data_nubi['Store']=='EMOS',['Store']]='ECOM RETAIL - EMOS'
data_nubi.loc[data_nubi['Store']=='KREASI NOSTRA MANDIRI - BOGOR, PT',['Store']]='ECOM RETAIL - SAYUR BOX JAKARTA'
data_nubi.loc[data_nubi['Store']=='KREASI NOSTRA MANDIRI - SURABAYA, PT',['Store']]='ECOM RETAIL - SAYUR BOX SURABAYA'
data_nubi.loc[data_nubi['Store']=='CIBINONG CENTER INDUSTRIAL ESTATE , PT',['Store']]='ECOM RETAIL - SAYUR BOX JAKARTA'
data_nubi.loc[data_nubi['Store']=='KREASI TANI LAKSMI - SURABAYA, PT',['Store']]='ECOM RETAIL - SAYUR BOX SURABAYA'
data_nubi.loc[data_nubi['Store']=='ECOM RETAIL - SWIFT BEKASI',['Store']]='ECOM RETAIL - TOKO NOW'
data_nubi.loc[data_nubi['Store']=='ECOM RETAIL - SWIFT JKT UTARA',['Store']]='ECOM RETAIL - TOKO NOW'
data_nubi.loc[data_nubi['Store']=='INOVASI DIGITAL NIAGA - KALIDERES, PT',['Store']]='ECOM RETAIL - BAYI NINJA JAKARTA'
data_nubi.loc[data_nubi['Store']=='INOVASI DIGITAL NIAGA - SURABAYA, PT',['Store']]='ECOM RETAIL - BAYI NINJA JAKARTA'
data_nubi.loc[data_nubi['Store']=='INDOPASIFIK TEKNOLOGI MED INDONESIA, PT',['Store']]='ECOM RETAIL - INDOPASIFIK FARMA MEDIKA INDONESIA'
data_nubi.loc[data_nubi['Store']=='ECOM RETAIL - LIFEPACK',['Store']]='ECOM RETAIL - INDOPASIFIK FARMA MEDIKA INDONESIA'
data_nubi.loc[data_nubi['Store']=='SAYUR BOX',['Store']]='ECOM RETAIL - SAYUR BOX JAKARTA'
data_nubi.loc[data_nubi['Store']=='TANIHUB',['Store']]='ECOM RETAIL - TANIHUB'

## ini run
data_all['Store'] = data_all['Store'].astype(str).str.replace('JD Indonesia - Nutrimart', 'JD Indonesia', regex = False)

data_all = data_all[data_all['Store'].isin(['JD Indonesia', 'Lazada', 'Bukalapak', 'Blibli', 'Tokopedia',
       'Shopee', 'Elevenia', 'Nutrimart', 'Order Online','Aladin Mall','TikTok', 'Orami Shopping'])]
data_all = data_all.append(data_nubi, ignore_index = True, sort = False)

indeks = data_all[data_all['Store'].isin(['JD Indonesia', 'Lazada', 'Bukalapak', 'Blibli', 'Tokopedia',
       'Shopee', 'Elevenia','Aladin Mall','TikTok', 'Orami Shopping'])].index.to_list()
data_all['Store Type'][indeks] = 'Marketplace'

indeks = data_all[data_all['Store'].isin(['Nutrimart', 'Order Online'])].index.to_list()
data_all['Store Type'][indeks] = 'Organic'

indeks = data_all[data_all['Order #'].astype(str).str.contains('Nubi')].index.to_list()
data_all['Store Type'][indeks] = 'Retail Online'

## ini run juga
indeks = data_all[data_all['Product Name'] == 'L-Men Bar Crunchy Chocolate (12sch)'].index.to_list()
data_all['Real Nama Produk'][indeks] = 'L-Men Bar Crunchy Chocolate 12sch'
data_all['Parent Item'][indeks] = 'L-Men Bar Crunchy Chocolate (12 Sch)'
data_all['Brand'][indeks] = 'L-Men'
data_all['Sub Brand'][indeks] = 'L-MEN POWDER'
data_all['Real SKU'][indeks] = '2306592173'
data_all['Parent SKU'][indeks] = '2306592173'

indeks = data_all[data_all['Product Name'] == 'Heavenly Blush Yogurt Drink To Go Peach (1 pc)'].index.to_list()
data_all['Brand'][indeks] = 'Heavenly Blush'

indeks = data_all[data_all['Brand'] == 'HB'].index.to_list()
data_all['Brand'][indeks] = 'Heavenly Blush'

## ini run juga
data_all['Region Group'] = np.nan

index = data_all[data_all['Region'].isin(['Dki Jakarta', 'Banten'])].index.to_list()
data_all['Region Group'][index] = 'Jabodetabek'

list_city = ['Kota Bekasi', 'Kabupaten Bekasi', 'Kab. Bekasi', 'Kota Bogor', 'Kabupaten Bogor', 'Kab. Bogor', 'Kota Depok', 'Kota Tangerang',
             'Kota Tangerang Selatan','Kabupaten Tangerang', 'Kab. Tangerang']

index = data_all[data_all['City'].isin(list_city)].index.to_list()
data_all['Region Group'][index] = 'Jabodetabek'

data_all['Region Group'] = data_all['Region Group'].fillna(data_all['Region'])

C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Qty. Invoiced'][indeks] = 0
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Qty. Invoiced'][indeks] = 0
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Total Net'][indeks] = data_all['Price List NFI'][indeks] * data_all['Qty. Invoiced'][indeks]
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Total Net'][indeks] = data_all['Price List NFI'][indeks] * data_all['Qty. Invoiced'][indeks]

Filling Date ====== 7/10

C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Regular Price'][indeks] = 0
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Selling Price'][indeks] = 0
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Selling Price'][indeks] = 0
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Selling Price'][indeks] = 0
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Regular Price'][indeks] = 0
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Regular Price'][indeks] = 0
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Selling Price'][indeks] = 0
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Selling Price'][indeks] = 0
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Regular Price'][indeks] = 0
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Regular Price'][indeks] = 0
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Real SKU'][indeks] = data_nubi['SKU'][indeks]

Filling Brand ====== 5/10

C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Real Nama Produk'][indeks] = data_nubi['Item Name'][indeks]

Empty DataFrame
Columns: [Sales Order ID, Order #, Customer Name, Order date, Paid Date, Order Status, Channel, Store, Currency Code, Warehouse Name, Regular Price, Selling Price, Subtotal, Gross Sales, SKU, Product Name, Qty. Invoiced, Date, Month, Year, True datetime, Week, Brand, Category, Quarter, Real SKU, Real Nama Produk, Sub Brand, Parent Item, Parent SKU, Price List NFI, Total, Total Net]
Index: []

[0 rows x 33 columns]

C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:157: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Brand'][indeks] = 'HiLo'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:155: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Brand'][indeks] = 'NS'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:169: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Store'][indeks] = 'Shopee Sell-In'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:169: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_nubi['Store'][indeks] = 'Shopee Sell-In'

data_nubi\data_nubi_2023-04-20.xlsx

C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:219: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Store Type'][indeks] = 'Marketplace'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:222: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Store Type'][indeks] = 'Organic'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:225: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Store Type'][indeks] = 'Retail Online'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Real Nama Produk'][indeks] = 'L-Men Bar Crunchy Chocolate 12sch'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Real Nama Produk'][indeks] = 'L-Men Bar Crunchy Chocolate 12sch'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:230: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Parent Item'][indeks] = 'L-Men Bar Crunchy Chocolate (12 Sch)'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:230: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Parent Item'][indeks] = 'L-Men Bar Crunchy Chocolate (12 Sch)'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:231: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Brand'][indeks] = 'L-Men'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:231: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Brand'][indeks] = 'L-Men'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:232: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Sub Brand'][indeks] = 'L-MEN POWDER'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:232: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Sub Brand'][indeks] = 'L-MEN POWDER'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:233: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Real SKU'][indeks] = '2306592173'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:233: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Real SKU'][indeks] = '2306592173'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:234: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Parent SKU'][indeks] = '2306592173'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:234: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Parent SKU'][indeks] = '2306592173'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:237: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Brand'][indeks] = 'Heavenly Blush'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:240: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Brand'][indeks] = 'Heavenly Blush'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:240: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Brand'][indeks] = 'Heavenly Blush'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:246: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Region Group'][index] = 'Jabodetabek'
C:\Users\steven.nathanael\AppData\Local\Temp\ipykernel_17600\3248999943.py:252: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_all['Region Group'][index] = 'Jabodetabek'

0         2022-01-01 00:00:00
1         2022-01-01 00:00:00
2         2022-01-01 00:00:00
3         2022-01-01 00:00:00
4         2022-01-01 00:00:00
                  ...
2360499   2023-03-23 09:03:00
2360500   2023-03-21 18:30:00
2360501   2023-03-11 17:41:00
2360502   2023-03-04 08:19:00
2360503   2023-03-27 10:15:00
Name: True datetime, Length: 2360504, dtype: datetime64[ns]